### ISSUE TITLE
Does not work on 64bits

### ISSUE THREAD

**Issue by revlysJ** [danjperron/BitBangingDS18B20#16]
Hello,

Thanks for this really helpful lib!

I've tested it on RPI 2,3,4 with buster 32bits, it works fine.
But on buster 64bits, at best it does nothing, at worse its stuck the whole system.

Is there a way to make it compliant with 64bits ?
Thanks you.

**Comment by danjperron** [comment]
I never tested it on 64bits.  
I will need to test it tonight. The only 64 bits PI4 are on my cluster.  I did compile it without error. The only problem I got was  to use 'sudo'. But since I don't have sensor on the cluster I can't check if the code is ok.

What I found on my ubuntu 64 bits Pi4,
 - /dev/mem and /dev/gpiomem are only available on root.  ( I will need to change this)
 - In gcc , int are 32 bits , long are 64 bits.  ( I will need to check my code to be sure that I'm using the correct size)
 -  when I check the GPIO map I got 
     for /dev/gpiomem
     `BCM GPIO BASE= fe000000
gpio map = 0xffff81b63000
gpio = 0xffff81b63000
`

   for /dev/mem
   `BCM GPIO BASE= fe000000
gpio map = 0xffff92e53000
gpio = 0xffff92e53000`
  

I will download ubuntu 64 bits tonight!

**Comment by danjperron** [comment]
@ revlysJ 
 
I update the github!  It is now compatible with my Pi4 ubuntu 64 bits.

Je vois que tu es en France. Je suis québécois alors si tu as des problèmes tu peux me parler en français.
Le problème est le fichier "ranges" qui est différent. J'ai changé la structure pour la version  64 bits avec __arch64__

Il y a aussi le problème de la dimension pour  le type long.

N.B. la version Ubuntu doit être utilisé avec la commande sudo puisque les fichiers /dev/gpiomem et /dev/mem sont seulement avec la permission "root".

En espérant le tout à ton entière satisfaction.

Daniel

**Comment by revlysJ** [comment]
Bonjour Daniel,

Comment ça va au Québec ?

Merci pour la mise à jour.
J'ai pu tester ce matin, tout semble fonctionner correctement !

J'utilise ta lib sous "Raspberry Pi OS Lite"  déjà avec la commande sudo car j'ai d'autres dépendances qui en ont aussi besoin.
Du coup, j'ai juste eu à relancer mon script d'installation des dépendances pour mettre ta version à jour, et tout roule maintenant.
Merci !

Je m'en doutais (un peu) pour le dimensionnement du type long, mais je n'aurais pas pensé au fichier "ranges".

Merci encore pour tout,
En te souhaitant le meilleur dans cette époque que nous traversons.

Aimé.
