### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by zhhz** [danjperron/BitBangingDS18B20#2]
I'm getting an error when I compile it on a Raspberry PI 2

gcc: error: unrecognized option ‘-rlt’

Can you point me to the right direction?

Thanks.

**Comment by danjperron** [comment]
Oops typo!

Please  pull the new code

cd BitBangingDS18B20
git pull origin master

once it is done  compile the code using -lrt  instead of  -rlt

B.T.W. In the file DS18B20V2.c I add a define to compile specifically for Pi2.
If you want to compile for the other Pi please  add  "#undef PI2" after the "#define PI2" or remove the define.

If you want to compile the other c file for PI2 please add the method or just change the

#define BCM2708_PERI_BASE        0x20000000
for
#define BCM2708_PERI_BASE        0x3F000000

**Comment by zhhz** [comment]
Wow, that's quick. Thanks man. Keep up the great job!

**Comment by zhhz** [comment]
Closed the issue, Dan's comments resolved the issue.
