### ISSUE TITLE
Can't work with DS18B20

### ISSUE THREAD

**Issue by user-mw** [danjperron/BitBangingDS18B20#4]
Hello.
I use file DS18B20Scan.c and file configDS18B20.c My sensor's id is 10-000802da8f1d. When I run compiled files with connecting sensor, I don't get any result with suggestion to enter resolution  (9bits and etc.). In addition I don't get any result with scan file. Even if I print **-f filename.txt** (which contains id) nothing happens. It is possible because id usually starts with "28" instead "10" like I have. Is it possible to modify your files and change resolution? I use Raspberry Pi 2 Model B.

**Comment by danjperron** [comment]
The familly code for DS18B20 is 0x28.

The familly code for DS1820 or DS18S20 is 0x10

Then it's not a DS18B20.

I don't have any DS1820 or DS18S20! I won't be able to check the timing difference

*** update ***  The timing is the same.

There is a lot of difference in the register also.
https://www.maximintegrated.com/en/app-notes/index.mvp/id/4377

**Comment by user-mw** [comment]
Thank you for quick answer. You are right. When I bought my sensor, they said that it was DS18B20. Now I have looked at it and it is exactly DS1820 (too small font size).  **Thank you again**.

**Comment by danjperron** [comment]
Ok It should work  but you need to modify the  function ReadSensor ( DS18B20Scan.c)

Force the resolution to be 9 bits 

line 419  -> resolution = 9;

and remove this

-   switch(ScratchPad[4])
-   {
-
-    case  0x1f: resolution=9;break;
-     case  0x3f: resolution=10;break;
 -    case  0x5f: resolution=11;break;
 -    case  0x7f: resolution=12;break;
 -  }

-   if(resolution==0) continue;

The last line was the guilty one !  Because register 4 is always 0xff on DS1820 the sensor was not found.

But you need to change the bits format on the data because it is not the same. I will let you do it!

Check the link I gave you ! it shows the DS1820 format.

**Comment by danjperron** [comment]
Just change the multiplicator factor 0.0625 by 0.5 on line  470 and 475

 temperature =  0.5 * (double) IntTemp.SHORT;
 printf("%02d bits  Temperature: %6.2f +/- 0.5 Celsius\n", resolution ,temperature);

**Comment by user-mw** [comment]
I think it is not possible, because I found a [Datasheet ](http://pdf1.alldatasheet.com/datasheet-pdf/view/58548/DALLAS/DS1820.html). And they say, that temperature is read as a 9–bit digital value. So it is nothing to solve. Thank you again.

**Comment by danjperron** [comment]
> So it is nothing to solve

If you do my two last comments it should work with the 9 bits precision. You should get 0.5 degree precision.

**Comment by user-mw** [comment]
Okey, I will try.

**Comment by user-mw** [comment]
Yes, it works great:
```
$ sudo ./DS18B20Scan -gpio 21
10-000802DA8F1D : 09 bits  Temperature:  23.00 +/- %0.5 Celsius
```

**Comment by danjperron** [comment]
I will take some times next week and add the detection of the sensor.

if the ID starts by 10 I will force 9 bits and multiply by 8 the value.

I will do it for DS18B20V2.c also
